### PR TITLE
Report current $ bill usage

### PR DESCRIPTION
**Pull request by paolodamico**
From user's feedback in the last billing period and @fuziontech's inspiration, we will now show the bill (in $) for your current running period to avoid any surprises.
- This PR introduces the backend changes required for this. Fetching the relevant information from Stripe to show it to the user.﻿

### CODE REVIEW

**Review by kpthatsme — APPROVED** [review]
lgtm – one question, would it make sense to just do this for all active accounts (i.e. non metered as well)? So whichever the plan type they have we always have the amount sending back

**Comment by paolodamico** [comment]
Oh sorry missed your comment @kpthatsme! I don't think it makes sense for users not on usage-based pricing, we only have a handful of them and their payment is fully flat, no surprises. POV?

**Comment by kpthatsme** [comment]
@paolodamico Yea I agree since the prices are flat it isn't necessary– def a nit but my pov was mainly from consistency and ease of API consumption since I think even non-metered bills should have a valid current_bill_amount (atleast intuitively).

**Comment by fuziontech** [comment]
Do the flat rate billing plans have a cap on events? Might be good to show where they are relative to the cap in that case.

Sent via Superhuman ( ***@***.*** )

**Comment by paolodamico** [comment]
Yes, and we do! We show you a nice progress bar with % of events used.

**Comment by fuziontech** [comment]
Nice! That was what I was going to suggest instead if they had a flat plan. Love it

Sent via Superhuman ( ***@***.*** )

**Pull request merged**
