### PR TITLE
Handle settings refactor

### PR DESCRIPTION
**Pull request by macobo**
Companion to https://github.com/PostHog/posthog/pull/7669

### CODE REVIEW

**Review by Twixes — CHANGES_REQUESTED** [review]
I think the core issue with the first try was that Cloud settings overrides are not really tested so the Cloud test suite in the main repo didn't flag the issue with e.g. `MULTI_TENANCY` just not working – I propose adding a test for that in a separate PR in this repo before merging the settings refactor, just to be 100% sure we don't have the same issue now _or_ in the future.

**Comment by macobo** [comment]
> I think the core issue with the first try was that Cloud settings overrides are not really tested so the Cloud test suite in the main repo didn't flag the issue with e.g. MULTI_TENANCY just not working – I propose adding a test for that in a separate PR in this repo before merging the settings refactor, just to be 100% sure we don't have the same issue now or in the future.

There are tests and they were failing: I updated the tests [here](https://github.com/PostHog/posthog/pull/7630/commits/657a8c7f4a918a2665d47a0158401d5cf41ec241) with the assumption on friday I would merge this PR before deploying (which I didn't).

**Comment by Twixes** [comment]
I see. So this will _work_. But… maybe with this whole cleanup of settings, we could clean the `cat multi_tenancy_settings.py >> settings.py` thing up too? Since, still, the copy scripts are not tested, that's why they were able to go out of sync. Is it feasible to apply a similar solution as used with `ee/settings.py` to, let's say `multi_tenancy/settings.py`? Relying on `try: import` in a single place instead of `cat` in various scripts.

**Comment by macobo** [comment]
Good idea that seems less fragile than what we have right now, will investigate.

**Review by fuziontech — APPROVED** [review]

**Review by Twixes — APPROVED** [review]
This is definitely clearer now

**Pull request merged**
