### PR TITLE
Remove outdated run code

### PR DESCRIPTION
**Pull request by paolodamico**
This code was outdated and out of use. Further, used only Postgres. Removing.

### CODE REVIEW

**Comment by paolodamico** [comment]
Let's merge #163 first so tests can run properly.

**Review by fuziontech — APPROVED** [review]

**Comment by fuziontech** [comment]
🤔 Why are the CI checks failing?

**Comment by paolodamico** [comment]
@fuziontech this is expected, I need to merge another PR here first that fixes the CI. Will make some time to get all these PRs in.

**Comment by fuziontech** [comment]
👍

**Pull request merged**
